defmodule ExMachina.Document do
  @moduledoc """
  Test model with polymorphic embed field using the actual polymorphic_embed library.
  """
  use Ecto.Schema
  import Ecto.Changeset
  import PolymorphicEmbed

  schema "documents" do
    field(:title, :string)
    field(:status, Ecto.Enum, values: [:draft, :published])
    field(:labels, {:array, Ecto.Enum}, values: [:internal, :public])

    belongs_to(:author, ExMachina.User)
    embeds_one(:metadata, ExMachina.DocumentMetadata)

    polymorphic_embeds_one(:content,
      types: [
        text: ExMachina.TextContent,
        image: ExMachina.ImageContent,
        video: ExMachina.VideoContent,
        note: ExMachina.NoteContent
      ],
      on_type_not_found: :raise,
      on_replace: :update
    )

    polymorphic_embeds_many(:attachments,
      types: [
        text: ExMachina.TextContent,
        image: ExMachina.ImageContent,
        video: ExMachina.VideoContent
      ],
      on_type_not_found: :raise,
      on_replace: :delete
    )
  end

  def changeset(document, attrs) do
    document
    |> cast(attrs, [:title, :status, :labels])
    |> cast_polymorphic_embed(:content)
    |> cast_polymorphic_embed(:attachments)
  end
end

defmodule ExMachina.DocumentMetadata do
  @moduledoc """
  Regular embedded schema holding a polymorphic embed, to exercise
  polymorphic fields reached through embed recursion.
  """
  use Ecto.Schema
  import PolymorphicEmbed

  @primary_key false
  embedded_schema do
    field(:source, :string)

    polymorphic_embeds_one(:banner,
      types: [
        text: ExMachina.TextContent,
        image: ExMachina.ImageContent
      ],
      on_type_not_found: :raise,
      on_replace: :update
    )
  end
end

defmodule ExMachina.TextContent do
  @moduledoc """
  Text content type for polymorphic embed
  """
  use Ecto.Schema
  import Ecto.Changeset

  @primary_key false
  embedded_schema do
    field(:body, :string)
  end

  def changeset(struct, attrs) do
    cast(struct, attrs, [:body])
  end
end

defmodule ExMachina.ImageContent do
  @moduledoc """
  Image content type for polymorphic embed
  """
  use Ecto.Schema
  import Ecto.Changeset

  @primary_key false
  embedded_schema do
    field(:url, :string)
    field(:alt_text, :string)
    field(:taken_on, :date)
    field(:taken_at, :time)
  end

  def changeset(struct, attrs) do
    cast(struct, attrs, [:url, :alt_text, :taken_on, :taken_at])
  end
end

defmodule ExMachina.VideoContent do
  @moduledoc """
  Video content type for polymorphic embed
  """
  use Ecto.Schema
  import Ecto.Changeset

  @primary_key false
  embedded_schema do
    field(:url, :string)
    field(:duration, :integer)
    field(:published_at, :utc_datetime)
  end

  def changeset(struct, attrs) do
    cast(struct, attrs, [:url, :duration, :published_at])
  end
end

defmodule ExMachina.NoteContent do
  @moduledoc """
  Content type with an autogenerated primary key, which PolymorphicEmbed
  refuses to dump unless the value went through cast_polymorphic_embed.
  """
  use Ecto.Schema

  @primary_key {:id, :binary_id, autogenerate: true}
  embedded_schema do
    field(:note, :string)
  end
end
