defmodule ExMachina.TestFactory do
  use ExMachina.Ecto, repo: ExMachina.TestRepo

  def custom_factory do
    %ExMachina.Custom{
      non_autogenerated_id: 1,
      name: "Testing"
    }
  end

  def user_factory do
    %ExMachina.User{
      name: "John Doe",
      admin: false,
      articles: [],
      best_article: nil
    }
  end

  def publisher_factory do
    %ExMachina.Publisher{
      pub_number: sequence("PUB_23")
    }
  end

  def article_factory do
    %ExMachina.Article{
      title: "My Awesome Article",
      author: build(:user)
    }
  end

  def comment_with_embedded_assocs_factory do
    %ExMachina.Comment{}
  end

  def invalid_cast_factory do
    %ExMachina.InvalidCast{}
  end

  def user_map_factory do
    %{
      id: 3,
      name: "John Doe",
      admin: false
    }
  end

  def document_factory do
    %ExMachina.Document{
      title: "Test Document",
      content: %{
        __type__: "text",
        body: "Sample text content"
      },
      metadata: %{
        author: "Test Author",
        created_at: "2024-01-01"
      }
    }
  end

  def document_with_image_factory do
    %ExMachina.Document{
      title: "Image Document",
      content: %{
        __type__: "image",
        url: "https://example.com/image.jpg",
        alt_text: "Test image"
      }
    }
  end
end
