defmodule ExMachina.TestFactory do
  use ExMachina.Ecto,
    repo: ExMachina.TestRepo,
    cast_value: &ExMachina.TestFactory.custom_cast/3

  def custom_cast(field_type, value, _struct) do
    # Skip casting for PolymorphicEmbed types - they're handled by the changeset
    if polymorphic_embed_type?(field_type) do
      value
    else
      case Ecto.Type.cast(field_type, value) do
        {:ok, value} -> value
        _ -> raise "Failed to cast value"
      end
    end
  end

  # Check if field type is from polymorphic_embed library
  defp polymorphic_embed_type?({:parameterized, PolymorphicEmbed, _}), do: true
  defp polymorphic_embed_type?(_), do: false

  def custom_factory do
    %ExMachina.Custom{
      non_autogenerated_id: 1,
      name: "Testing"
    }
  end

  def user_factory do
    %ExMachina.User{
      name: "John Doe",
      admin: false,
      articles: [],
      best_article: nil
    }
  end

  def publisher_factory do
    %ExMachina.Publisher{
      pub_number: sequence("PUB_23")
    }
  end

  def article_factory do
    %ExMachina.Article{
      title: "My Awesome Article",
      author: build(:user)
    }
  end

  def comment_with_embedded_assocs_factory do
    %ExMachina.Comment{}
  end

  def invalid_cast_factory do
    %ExMachina.InvalidCast{}
  end

  def user_map_factory do
    %{
      id: 3,
      name: "John Doe",
      admin: false
    }
  end

  def document_factory do
    %ExMachina.Document{
      title: "Test Document",
      content: %ExMachina.TextContent{
        body: "Sample text content"
      }
    }
  end

  def document_with_image_factory do
    %ExMachina.Document{
      title: "Image Document",
      content: %ExMachina.ImageContent{
        url: "https://example.com/image.jpg",
        alt_text: "Test image"
      }
    }
  end
end
