# This file is synced with beam-community/common-config. Any changes will be overwritten.

name: Common Config

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/common-config.yaml
  repository_dispatch:
    types:
      - common-config
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch: {}

concurrency:
  group: Common Config

jobs:
  Sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24

      - name: Setup Elixir
        uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1.24.1
        with:
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          elixir-version: "1.19"
          otp-version: "27.0"

      - name: Sync
        uses: beam-community/actions-sync@fea49a55e9867e5448fd2822b207177dd8ebba38 # v1.14.1
        with:
          commit-message: "chore: sync files with beam-community/common-config"
          pr-enabled: true
          pr-labels: common-config
          pr-title: "chore: sync files with beam-community/common-config"
          pr-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          sync-auth: doomspork:${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          sync-tree: latest
          sync-repository: github.com/beam-community/common-config.git
          config-file: .github/common-config.yaml
