# This file is synced with beam-community/common-config. Any changes will be overwritten.

name: PR

on:
  merge_group:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

jobs:
  Commits:
    name: Conventional Commits
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}

    permissions:
      contents: read
      pull-requests: read

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - uses: wagoid/commitlint-github-action@b948419dd99f3fd78a6548d48f94e3df7f6bf3ed # v6
        with:
          configFile: .commitlintrc.yml

  Labels:
    name: Assign Labels
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: mauroalderete/action-assign-labels@671a4ca2da0f900464c58b8b5540a1e07133e915 # v1
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          conventional-commits: |
            conventional-commits:
              - type: 'fix'
                nouns: ['FIX', 'Fix', 'fix']
                labels: ['bug']
              - type: 'feature'
                nouns: ['FEAT', 'Feat', 'feat']
                labels: ['feature']
              - type: 'chore'
                nouns: ['CHORE', 'Chore', 'chore']
                labels: ['chore']
              - type: 'docs'
                nouns: ['DOCS', 'Docs', 'docs']
                labels: ['documentation']
              - type: 'ci'
                nouns: ['CI', 'Ci', 'ci']
                labels: ['ci']
